### ISSUE TITLE
Target Resolution for Linux computers

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#85] opened 2016-01-20 13:56 UTC
This problem has been effecting me for a while, but it's now interfering with one of the last steps on getting the JavaFX branch building. When I try to resolve mars.target on my Linux machines, I get the error message

Problems occurred while resolving the target contents
An error occurred while configuring the installed items
Preference node "http:_download.eclipse.org_tools_cdt_releases_8.7" has been removed.
session context was:(profile=TARGET_DEFINITION:resource:/org.eclipse.ice.target.mars/mars.target, phase=org.eclipse.equinox.internal.p2.engine.phases.Configure, operand=null --> [R]org.eclipse.cdt.feature.group 8.7.0.201506070905, action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.AddRepositoryAction)

This happens regardless of where in ICE I try to open the target from or what version of ICE I'm using, including the most recent unstable nightly. Once it occurs on a machine, it effects every instance of ICE on it.

**Comment by jayjaybillings** [comment] 2016-01-20 14:13
Here is something to try on Linux. It should take about 54min if I remember correctly.

1.) Delete ~/.m2 completely.
2.) Create a completely new workspace and checkout ICE from its developer menu.
3.) Pop open the target and/or try to build.

This doesn't happen on any of my Linux machines, but I'll try to check again to make sure. You might also need to merge the latest from next into your branch (which is a good idea anyway).

Let me know how this works.

**Comment by SmithRWORNL** [comment] 2016-01-20 14:31
Just tried this, same result. I'm in the process of merging next into my branch, but I used next for that attempt and I still ran into the same problem.

**Comment by jayjaybillings** [comment] 2016-01-20 14:32
Okay. One you get next merged in let me know and I'll give it a try.

**Comment by SmithRWORNL** [comment] 2016-01-20 14:49
I have them merged, so you can try it out, though I don't think the issue is related to my branch.

**Comment by jayjaybillings** [comment] 2016-01-21 20:56
Sorry Robert, I can't reproduce the problem. On two different machines the target from your branch has worked just fine on Linux. I'll be in tomorrow and can take a look if you want.

**Comment by jayjaybillings** [comment] 2016-01-23 02:11
Fixed this error by removing ~/.eclipse and creating a new workspace. I know you have some more bugs, but they are related to e(fx)clipse if I remember correctly and we can open another bug if needed.

**Closed by jayjaybillings** 2016-01-23 02:11 UTC
Labels: help wanted
