### ISSUE TITLE
'Destination Path Too Long' warning message during windows installation

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#296] opened 2016-11-29 17:04 UTC
During the installation of eclipse/ice in Windows 10, I received the warning messages in the dialog windows in the attachment.
I’ve not tested eclipce/ice enough to find out the consequences of skipping the libraries in the attachment. When you click on the Cancel button, the whole installation is canceled. I wonder if that cancellation has any effects in the functionality of the eclipse/ice.

The attachment includes the work environment details.

[Destination Path Too Long warning message during windows installation.docx](https://github.com/eclipse/ice/files/619642/Destination.Path.Too.Long.warning.message.during.windows.installation.docx)

**Comment by jayjaybillings** [comment] 2016-11-29 19:40
That would definitely mess up the reflectivity bundle in Eclipse ICE - I think - because it is turning off support for rendering glazed lists in nattable. I'm not sure what to do about it though. 

@SmithRWORNL will you try to reproduce this please to make sure that is a general Windows thing?

**Comment by SmithRWORNL** [comment] 2016-11-29 19:42
I can confirm it's happening on all Windows machines, though it only happens on one of the files for me, not both.

**Comment by SmithRWORNL** [comment] 2016-11-29 20:44
@klaskyhb What file path were you unzipping ICE to? I was able to avoid this problem by simply changing the target directory from "ice unstable 20" to "ice" on my desktop. I suspect you were using something longer, which would explain why I only get the error on a single .pom file while it was happening to two whole folders for you. 

There is a way to opt in to using longer file paths in Windows 10, as described at the bottom of the page at http://answers.microsoft.com/en-us/windows/forum/windows_10-files/source-path-too-long-bug-in-windows-10/b0cb82b0-85c1-4fcf-81cd-041b2175563e?page=5 , but I don't think we should be telling people to manually edit their registries before installing ICE.

I think that the best we can do is to advise users to unzip ICE as far up their file system as possible and to use a destination folder with a short name like "ICE." If they absolutely require that it be installed deeper, we can point them to third party tools like the Long Path Tool, which I haven't tried but which can apparently be used in conjunction with 7-zip to handle the extraction.

**Comment by SmithRWORNL** [comment] 2016-11-29 21:18
@jayjaybillings It doesn't seem to be affecting the Reflectivity Model at all. I deleted the entire "features" top level folder in ICE, and I can manipulate the nattable. Giving it a waveVector file and running with the default values gets it stuck in an endless "Processing Form..." state, but I'm getting the same behavior even with a complete installation, so either I'm doing something wrong or it's an unrelated bug.

**Comment by jayjaybillings** [comment] 2016-11-30 03:11
@klaskyhb - Yes, I think that processing bug is a separate issue. We've had a lot of trouble with the Reflectivity bundle lately and I think it is probably in need of some maintenance. I'm glad to hear that the nattable seems to work though.


@SmithRWORNL - I think we should probably file a bug on Nattable too. The ultimate fix is not that we give users warning, but that the file names get changed or something similar is done. Will you go ahead please?


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by SmithRWORNL** [comment] 2016-11-30 13:16
@jayjaybillings I've filed a bug at https://bugs.eclipse.org/bugs/show_bug.cgi?id=508443

**Comment by jayjaybillings** [comment] 2016-11-30 14:48
@SmithRWORNL Okay, great. Thanks! Please add a note on this to our "Known Issues" page on the wiki ( and delete anything there that looks old while you're at it! ;-)). You should link to this ticket and the new bug you've filed, then close this ticket.

**Comment by SmithRWORNL** [comment] 2016-11-30 14:50
@jayjaybillings They suggested that I try out NatTable 1.4.0 to see if the issue persists. I'll give that a shot before adding it to our wiki, but I'll clean up the Known Issues either way.

**Comment by klaskyhb** [comment] 2016-11-30 15:32
@SmithRWORNL: I received the ‘Destination Path Too Long’ dialog when installing the ICE_SDK executable in the following path:
C:\Users\kpf\Documents\ice.sdk.product-win32.win32.x86_64


When trying to extract the file in the root directory:
![image](https://cloud.githubusercontent.com/assets/4369008/20758550/2ce567cc-b6e8-11e6-8474-be387633d107.png)

I got the following warning message, only:
![image](https://cloud.githubusercontent.com/assets/4369008/20758569/3f5541ac-b6e8-11e6-9b71-056f48608630.png)

**Comment by SmithRWORNL** [comment] 2016-11-30 16:14
Fixed by commit 90fdfca564e776530267c6ed8c97e38b12fa8dd0, which switched to a version of NatTable which lacks the long file paths causing the issue.

**Comment by jayjaybillings** [comment] 2016-11-30 16:17
@SmithRWORNL I'm reopening this because you have version numbers for the nattable bundles in 90fdca.

**Comment by SmithRWORNL** [comment] 2016-11-30 16:19
@jayjaybillings Can you explain what the issue with the version numbers is? I'm afraid I don't understand.

**Comment by jayjaybillings** [comment] 2016-11-30 16:20
Something like this

```xml
<unit id="org.eclipse.nebula.widgets.nattable.extension.poi.feature.feature.group" version="1.4.0.201606011907"/>
```

needs to be

```xml
<unit id="org.eclipse.nebula.widgets.nattable.extension.poi.feature.feature.group" version="0.0.0"/>
```

**Comment by SmithRWORNL** [comment] 2016-11-30 16:51
Target version numbers have been corrected by commit d322eefaead223ac4c33038088e85e96f2f9bc10.

**Comment by jayjaybillings** [comment] 2016-11-30 18:29
Thanks @SmithRWORNL. Will you confirm that a build with the new target version numbers does not have the file errors?

**Comment by SmithRWORNL** [comment] 2016-11-30 19:35
@jayjaybillings Checked with both a locally built executable and with the latest nightly off the build server, and neither is experiencing the issue for what I would consider a reasonable installation directory, C:/Users/username/Desktop/ice.sdk.product-win32.win32.x86_64

Of course, since this is an issue with Windows, there will always be some degenerate case where the issue reappears.

**Comment by jayjaybillings** [comment] 2016-11-30 19:53
I feel like the use of the word "degenerate" is the best way to describe that operating system... ;-) Thanks. Closed!

**Closed by jayjaybillings** 2016-11-30 19:53 UTC
Labels: 2.2.1
