### ISSUE TITLE
Updates for tutorial (ice-xsede)

### ISSUE THREAD

**Issue by anarak** [eclipse/ice#321] opened 2017-01-25 22:00 UTC
The following are suggestions for a better clarity of the tutorial.

1.2 Installation: using USB stick is one way of getting the source code, maybe it's worth putting description about getting the source from the web?
1.2 Installation: adding exact file names to the list of what is provided in the USB stick would help. For example: 'A clone of the ICE git repository (ice-repository.zip)' and etc.
1.2.1 ICE Installation: 
step 1: maybe the word 'product' can be omitted from 'ice-product*.zip'? There's no 'product' word in the current versions.
step 2: can the executable be specified with its name?
2.1.1 Creating the Plug-in Project: word 'Project' is missing from the 'ICE Item Creation Wizard'. Should be 'ICE Item Project Creation Wizard'.
2.1.1 Creating the Plug-in Project: the app popped up 'ICE Item Project Creation Wizards', in the manual it's 'ICE Item Creation Wizards'. Then in the app it's 'New ICE Item Project', in the manual 'ICE Item Creation Wizard' (screenshot is attached)
![screenshot from 2017-01-25 16-57-32](https://cloud.githubusercontent.com/assets/25353166/22311063/b0f697da-e31f-11e6-87c4-944c8ac4b9dd.png)
2.1.1 After creating the Fern Plug-in Project an Overview window appears in ICE. Either add a screenshot of that view or mention in the tutorial about this appearance, so that users are informed.
2.1.2 The Fern model: 'export string' is not italicised as other variables.
2.2.2 Step 2: the 'Package Explorer' should be 'Project Explorer'.

**Comment by SmithRWORNL** [comment] 2017-01-26 13:10
@anarak The docs for the tutorial are written in Latex and are in the ICE repo itself (e.g. under the newItemGeneration project). Let us know if you need help editing them.

**Comment by anarak** [comment] 2017-01-26 16:01
Add an explanation to tutorial specifying that

1. ICE is an Eclipse application
2. ICE git repository is a git repository for bundles needed to be added to ICE application
3. using different versions of ICE (application) and bundles will cause errors
4. 2.2.1-2 this step is about creating a synchronized project through remote connection to a directory. Currently, there is no access to remote host (expired). Add an update on the access status to tutorial or keep the access available to users.
5. adding a point of contact for obtaining host information details like user, pwd, host to tutorial for 2.2.1.
6. the first picture on page 17 looked different from what I had: the list in 'Project Type' had different number of folders (less of them) from the tutorial's picture. Add a sentence saying that the list may differ if it may.

**Comment by anarak** [comment] 2017-01-27 16:35
After completing 4.1.2 had the following error:
![screenshot from 2017-01-27 11-33-31](https://cloud.githubusercontent.com/assets/25353166/22378760/a75e2d26-e484-11e6-8e21-c315fced257b.png)

**Comment by SmithRWORNL** [comment] 2017-01-27 17:13
@anarak I couldn't reproduce the bug for section 4.1.2 on the latest unstable nightly build. What version of ICE are you using?

**Comment by anarak** [comment] 2017-01-27 18:31
@SmithRWORNL it's:
Version: next
Build id: 20170118

**Comment by SmithRWORNL** [comment] 2017-01-27 18:42
@anarak What version of Java? You need Java 8 in order to have JavaFX for the geometry and mesh editors.

**Comment by anarak** [comment] 2017-01-27 18:53
@SmithRWORNL it's:
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b16)
OpenJDK 64-Bit Server VM (build 25.111-b16, mixed mode)

**Comment by jayjaybillings** [comment] 2017-01-27 19:08
@SmithRWORNL I bet it is the default Fedora build of OpenJDK that does not contain the necessary SWT jars.

I think we need to update the wiki page to reflect this problem with the Fedora OpenJDK as well. http://wiki.eclipse.org/Getting_ICE

**Comment by SmithRWORNL** [comment] 2017-01-27 19:26
@anarak 

Try downloading https://jdk8.java.net/download.html

Then do

alternatives --install /usr/bin/java java /path/to/java/jre/bin/java 3

alternatives --config java

Then type the number of the new JDK you just downloaded (3, in this case).

That should get you set up with the correct JDK that has all the JavaFX jars in it. Then you can restart ICE and try opening the Geometry Editor again.

**Comment by anarak** [comment] 2017-01-30 15:47
@SmithRWORNL, that solved the problem with the Geometry Editor. As Jay said this must be updated in the wiki.

**Comment by anarak** [comment] 2017-01-30 16:26
1. add a screenshot of default ICE view after opening the Geometry Editor at the end of 4.1.2 so that users know how the Geometry Editor looks like.
2. in 4.1.3 clicking on the shape's name in the Shapes View didn't make the shape's color turn red.
3. in 4.1.3 selections of the shapes in the Shape View didn't activate the Transformation View in the lower left corner.
4. in 4.1.3 when adding a Duplicate Shape to union it won't show that shape until adding next primitive shape outside of the union.

**Comment by anarak** [comment] 2017-01-31 15:18
1. in 3.2 p.30 my view for the Figure 3.3 was different which included different packages. I only had to add a couple of packages to the imported packages and no class to import. What packages should've been imported exactly and what class?
2. in 3.2 p.31 when launching new instance of ICE the, there was no fern plugin in 'Plugin Addition Selection'.

**Comment by anarak** [comment] 2017-01-31 20:16
1. add a description of where to store all the distributions (ICE, VisIt), data folders, git repos, etc on a machine, also, the location of workspaces for ICE and new instances of ICE.

**Comment by SmithRWORNL** [comment] 2017-02-01 19:09
@anarak closed this incorrectly by accident.

**Comment by anarak** [comment] 2017-02-01 22:18
1. in 4.4.1 p.62 omit ICEFiles from ICEFiles/default and ICEFiles/itemDB and mention that those imported folders will be empty (without data files) and that the packages in Project Explorer will have the same view as in the Package Explorer.
2. in 4.4.1 p. 62 there is no 'Next' button no transition to the dialog window shown in p. 63., but only 'OK'.
3. in 4.4.1 p 64 the 'add remote file' button in Visualization File Viewer doesn't open anything.

**Comment by anarak** [comment] 2017-02-02 18:46
1. in 4.4.4 'pseudocolor, contour, or volume' buttons are not showing after right-click inside the display area. The VisIt Plot Viewer is disabled, so no access to those button from there too.
2. in 4.4.5 there is no time slider widget at the bottom of the Plot Editor, similar controls in the VisIt File Viewer are disabled.
3. in 4.4.6 'Execute a Python script' doesn't open anything.
4. in 5.1.2 p.75 the first picture shows that the chosen project's name is 'fern', but according to tutorial the project's name goes as 'org.eclipse.ice.fern'.
5. in p.75 is there a need to press 'Apply' before 'OK?
6. in p.77 the picture shows only two folders: fern and itemDB whereas in my view it showed all the projects. Add description about that or update the picture.

**Comment by anarak** [comment] 2017-02-07 13:14
1. add a description about possible problem with VisIt in Linux systems. See #336.

**Comment by anarak** [comment] 2017-02-08 14:41
1. in 2.2.6 in the first paragraph specify that ICE launcher is meant to be ICE Job Launcher.

**Closed** 2019-08-28 14:32 UTC
Labels: bug, wontfix
